apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
    name: app-service
spec:
  type: LoadBalancer
  selector:
    name: app
    type: netapi
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30008
